# Generated by Django 4.2.6 on 2023-10-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='social',
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_id',
            field=models.IntegerField(default=-1, verbose_name='oauth_id'),
        ),
    ]
