# Generated by Django 4.2.5 on 2023-10-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_remove_customuser_social_customuser_social_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=200)),
            ],
        ),
    ]
