# Generated by Django 4.2.5 on 2023-10-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_puzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=2000)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='long',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_string', models.CharField(max_length=500)),
                ('puzzle_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='puzzle.puzzle')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='hunt_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='puzzle.hunt'),
        ),
    ]
