# Generated by Django 4.2.6 on 2023-10-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_hunt_puzzle_lat_puzzle_long_hint_puzzle_hunt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='radius',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hint',
            name='puzzle_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='puzzle.puzzle'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='hunt_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzle.hunt'),
        ),
    ]
