# Generated by Django 4.2.5 on 2023-10-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_hunt_puzzle_lat_puzzle_long_hint_puzzle_hunt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='radius',
            field=models.IntegerField(default=10),
        ),
    ]
