# Generated by Django 4.2.5 on 2023-10-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0005_puzzle_radius_alter_hint_puzzle_id_alter_hunt_id_and_more'),
    ]

    operations = [
    ]
