# Generated by Django 4.2.5 on 2023-10-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_merge_20231017_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hint',
            name='puzzle_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='puzzle.puzzle'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='hunt_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='puzzle.hunt'),
        ),
    ]
