# Generated by Django 4.2.5 on 2023-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_hunt_submitted_alter_hint_puzzle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='random_field',
            field=models.IntegerField(default=-1),
        ),
    ]
