# Generated by Django 4.2.5 on 2023-10-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_puzzle_random_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='random_field',
        ),
    ]
