# Generated by Django 3.2.22 on 2023-10-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0009_remove_puzzle_random_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='puzzle.customuser'),
        ),
    ]
