# Generated by Django 4.2.6 on 2023-10-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0010_alter_hunt_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
