# Generated by Django 4.2.6 on 2023-10-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0012_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='creator',
            new_name='player',
        ),
    ]
