# Generated by Django 4.2.6 on 2023-10-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0014_session_current_hints_used_session_total_hints_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='finished_puzzle',
            field=models.BooleanField(default=False),
        ),
    ]
