# Generated by Django 3.2.22 on 2023-11-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0016_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hunt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.hunt'),
        ),
    ]
