# Generated by Django 3.2.22 on 2023-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0017_alter_session_hunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='comments',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
